### ISSUE TITLE
规则不能去ios youtube app广告吗？

### ISSUE THREAD

**Issue by q345296237** [Shu-Ji/shadowrocket-anti-ad#2]
规则不能去ios youtube app广告吗？

**Comment by Shu-Ji** [comment]
> 规则不能去ios youtube app广告吗？

目前配置中有去除YouTube的规则(DOMAIN-SUFFIX,googlevideoads.com,REJECT)，我的iOS版YouTube是没有广告的，检查一下是否配置正确哦？
