### ISSUE TITLE
知乎开屏广告能屏蔽吗？

### ISSUE THREAD

**Issue by chenhuawu** [Shu-Ji/shadowrocket-anti-ad#3]
我抓包看到知乎的开屏广告，但是我只能按屏蔽域名来屏蔽开屏广告，但有时候也不起作用

**Comment by Shu-Ji** [comment]
大部分APP的开屏广告目前都无法屏蔽。
知乎有少量规则收录，如果你有广告域名，可以发出来看看，不确定不起作用是不是知乎会有换广告域名的情况？
