### ISSUE TITLE
添加tiktok规则

### ISSUE THREAD

**Issue by wlcp** [Shu-Ji/shadowrocket-anti-ad#4]
可以把tiktok的规则也更新进入吗

https://raw.githubusercontent.com/Semporia/TikTok-Unlock/master/Shadowrocket/TikTok.list

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by Shu-Ji** [comment]
@10o0 tiktok的ip应该是海外的吧？海外的是默认会走代理的
